# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addenergyscan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 1212)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 710, 631, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_energy_high = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_energy_high.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_energy_high.setObjectName("lab_energy_high")
        self.horizontalLayout.addWidget(self.lab_energy_high)
        self.input_energy_high = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.input_energy_high.setMinimum(2100)
        self.input_energy_high.setMaximum(11000)
        self.input_energy_high.setSingleStep(50)
        self.input_energy_high.setProperty("value", 5000)
        self.input_energy_high.setObjectName("input_energy_high")
        self.horizontalLayout.addWidget(self.input_energy_high)
        self.lab_energy_low = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_energy_low.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_energy_low.setObjectName("lab_energy_low")
        self.horizontalLayout.addWidget(self.lab_energy_low)
        self.input_energy_low = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.input_energy_low.setMinimum(2100)
        self.input_energy_low.setMaximum(11000)
        self.input_energy_low.setSingleStep(50)
        self.input_energy_low.setProperty("value", 4500)
        self.input_energy_low.setObjectName("input_energy_low")
        self.horizontalLayout.addWidget(self.input_energy_low)
        self.lab_energy_step = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_energy_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_energy_step.setObjectName("lab_energy_step")
        self.horizontalLayout.addWidget(self.lab_energy_step)
        self.input_energy_step = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.input_energy_step.setMinimum(2)
        self.input_energy_step.setMaximum(100)
        self.input_energy_step.setProperty("value", 10)
        self.input_energy_step.setObjectName("input_energy_step")
        self.horizontalLayout.addWidget(self.input_energy_step)
        self.lab_energy_gap = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_energy_gap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_energy_gap.setObjectName("lab_energy_gap")
        self.horizontalLayout.addWidget(self.lab_energy_gap)
        self.energy_gap = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.energy_gap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.energy_gap.setLineWidth(3)
        self.energy_gap.setSmallDecimalPoint(False)
        self.energy_gap.setDigitCount(4)
        self.energy_gap.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.energy_gap.setObjectName("energy_gap")
        self.horizontalLayout.addWidget(self.energy_gap)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_energy_high.setText(_translate("MainWindow", "Energy High: "))
        self.lab_energy_low.setText(_translate("MainWindow", "Energy Low: "))
        self.lab_energy_step.setText(_translate("MainWindow", "Steps: "))
        self.lab_energy_gap.setText(_translate("MainWindow", "Gap: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
